---
- name: "docker-jenkins: Create remote dir"
  synchronize:
    src: "Dockerfiles/"
    dest: "{{ docker_Dockerfiles_loc }}/"

- name: "docker-jenkins: Setup groovy script for jenkins-master"
  template:
    src: "jenkins-master/security.groovy.j2"
    dest: "{{ docker_Dockerfiles_loc }}/jenkins-master/security.groovy"

- name: "docker-jenkins: Push all required images in the local registry"
  docker_image:
    name: "{{ docker_image.name }}"
    path: "{{ docker_image.path }}"
    dockerfile: "{{ docker_image.dockerfile }}"
    push: yes
    repository: "{{ docker_registry_URI }}/{{ docker_image.name }}"
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: docker_image

- name: "docker-jenkins: Create docker container for jenkins"
  docker_container:
    name: "jenkins-master"
    image: "jenkins/jenkins:lts"
    state: started
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    working_dir: /var/www

- name: Wait until the password file is present"
  wait_for:
    path: "/var/lib/docker/volumes/jenkins_home/_data/secrets/initialAdminPassword"

- name: "docker-jenkins: Register password"
  command: "cat /var/lib/docker/volumes/jenkins_home/_data/secrets/initialAdminPassword"
  register: jenkins_password

- name: "docker-jenkins: Print password"
  debug:
    msg: "{{ jenkins_password.stdout_lines[0] }}"
