---
- name: "docker-jenkins: Create remote dir"
  synchronize:
    src: "Dockerfiles/"
    dest: "{{ docker_Dockerfiles_loc }}/"

- name: "docker-jenkins: Setup groovy script for jenkins-master"
  template:
    src: "jenkins-master/security.groovy.j2"
    dest: "{{ docker_Dockerfiles_loc }}/jenkins-master/security.groovy"

- name: "docker-jenkins: Setup main config.xml script for jenkins-master"
  template:
    src: "jenkins-master/config.xml.j2"
    dest: "{{ docker_Dockerfiles_loc }}/jenkins-master/config.xml"

- name: "docker-jenkins: Push all required images in the local registry"
  docker_image:
    name: "{{ docker_image.name }}"
    path: "{{ docker_image.path }}"
    dockerfile: "{{ docker_image.dockerfile }}"
    push: yes
    repository: "{{ docker_registry_URI }}/{{ docker_image.name }}"
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: docker_image

- name: "docker-jenkins: Push the predefined jobs and pipelines" # Jenkins AFAIK will not automatically pick them up if they differ - perhaps a restart notify? 
  synchronize:
    src: "jenkins_master/"
    dest: "{{ jenkins_master_persistent_volume }}/"

- name: "docker-jenkins: Replace the entry in the build_test_emoji for the ansible inventory"
  replace:
    path: "{{ jenkins_master_persistent_volume }}/jobs/built_test_emoji/config.xml"
    regexp: '\`basename --suffix=:8080 \$JENKINS_URL\`'
    replace: "{{ ec2_metadata.results[0].tagged_instances[0].public_ip }}"
  

- name: "docker-jenkins: Create and start a docker container to act as jenkins master"
  docker_container:
    name: "jenkins-master"
    image: "{{ docker_registry_URI }}/jenkins-master"
    state: started
    ports:
      - "8080:8080"
    volumes:
      - "{{ jenkins_master_persistent_volume }}:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
