---
- name: "docker-jenkins: Create remote dir"
  synchronize:
    src: "Dockerfiles/"
    dest: "{{ docker_Dockerfiles_loc }}/"

- name: "docker-jenkins: Setup groovy script for jenkins-master"
  template:
    src: "jenkins-master/security.groovy.j2"
    dest: "{{ docker_Dockerfiles_loc }}/jenkins-master/security.groovy"

- name: "docker-jenkins: Push all required images in the local registry"
  docker_image:
    name: "{{ docker_image.name }}"
    path: "{{ docker_image.path }}"
    dockerfile: "{{ docker_image.dockerfile }}"
    push: yes
    repository: "{{ docker_registry_URI }}/{{ docker_image.name }}"
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: docker_image

- name: "docker-jenkins: Create and start a docker container to act as jenkins master"
  docker_container:
    name: "jenkins-master"
    image: "{{ docker_registry_URI }}/jenkins-master"
    state: started
    ports:
      - "8080:8080"
    volumes:
      - "{{ jenkins_master_persistent_volume }}:/var/jenkins_home"
