---
- name: "docker-registry: Setup local registry"
  docker_container:
    name: "docker-registry"
    image: "registry"
    state: started
    ports:
      - "{{ docker_registry_port }}:{{ docker_registry_port }}"
    volumes:
      - registry_home:/images
