---
- name: "docker-service: Make sure we can connect to the API"
  lineinfile:
    path: "/lib/systemd/system/docker.service"
    regex: "^ExecStart=*"
    line: "ExecStart=/usr/bin/dockerd -H fd://"
  notify: "Restart docker service and reload daemon"

- name: "docker-service: Make sure docker-ce is setup"
  service:
    state: started
    name: "docker"
    enabled: yes
