---
sg_groups:
  - name: "jenkins"
    description: "CICD Test - Allow access to jenkins"
    rules: 
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
  - name: "ssh"
    description: "CICD Test - Allow access to sshd"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  - name: "emoji_npm"
    description: "CICD Test - Allow access to the emoji app"  
    rules:
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: 0.0.0.0/0
