---
sg_groups:
  - name: "jenkins"
    description: "CICD Test - Allow access to jenkins"
    rules: 
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
  - name: "ssh"
    description: "CICD Test - Allow access to sshd"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  - name: "emoji_npm"
    description: "CICD Test - Allow access to the emoji app"  
    rules:
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: 0.0.0.0/0

# Most of these should be inventory variables , but for now we're OK.
ec2_hosts:
  - name: "main_host"
    description: "Test CICD"
    instance_tag: "Test"
    image: ami-09f0b8b3e41191524
    key_name: CICD
    instance_type: t2.large # We need this size to spin up all the containers
    exact_count: 1
    group: ['jenkins', 'ssh', 'emoji_npm']
    region: "eu-west-1"
