---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws_host

- hosts: docker_hosts
  become: yes
  roles:
    - docker_engine
  vars:
    ansible_python_interpreter: "/usr/bin/python3" # (#19605)
  tags: [setup_docker_host]

- hosts: docker_hosts
  become: yes
  roles:
    - docker_CICD
  vars:
    ec2_metadata: "{{ hostvars['localhost']['ec2_metadata'] }}"
  tags: [setup_docker_host]
